---
name: 'Setup multi-gitter'
author: Yevhen Fabizhevskyi
description: 'This action installs multi-gitter CLI tool.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'multi-gitter version.'
    required: false
    default: '0.43.2'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        MULTI_GITTER_INSTALLED=$(if command -v multi-gitter >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "MULTI_GITTER_INSTALLED=$MULTI_GITTER_INSTALLED" >> $GITHUB_OUTPUT
        multi_gitter_path="$GITHUB_WORKSPACE/multi-gitter"
        mkdir -p $multi_gitter_path
        echo "MULTI_GITTER_PATH=$multi_gitter_path" >> $GITHUB_OUTPUT
      shell: sh
    - name: Download multi-gitter
      if: ${{ steps.info.outputs.MULTI_GITTER_INSTALLED == 'false' }}
      run: curl https://raw.githubusercontent.com/lindell/multi-gitter/master/install.sh --output install.sh --silent
      shell: sh
      working-directory: ${{ steps.info.outputs.MULTI_GITTER_PATH }}
    - name: Fix bug
      if: ${{ steps.info.outputs.MULTI_GITTER_INSTALLED == 'false' && runner.os == 'Windows' }}
      run: Set-Content -Path "install.sh" -Value (Get-Content -Path "install.sh" | Select-String -Pattern 'adjust_format\r\n\r\n' -NotMatch)
      shell: pwsh
      working-directory: ${{ steps.info.outputs.MULTI_GITTER_PATH }}
    - name: Install multi-gitter
      if: ${{ steps.info.outputs.MULTI_GITTER_INSTALLED == 'false' }}
      run: |
        cat install.sh
        install.sh -d v${{ inputs.version}}
      shell: sh
      working-directory: ${{ steps.info.outputs.MULTI_GITTER_PATH }}
