---
name: "Setup multi-gitter"
author: Yevhen Fabizhevskyi
description: "This action installs multi-gitter CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "multi-gitter version."
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      run: |
        already_installed=$(if command -v multi-gitter >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "already-installed=${already_installed}" >> "$GITHUB_OUTPUT"
        multi_gitter_path="${GITHUB_WORKSPACE}/multi-gitter"
        mkdir -p "${multi_gitter_path}"
        echo "target-path=${multi_gitter_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Install multi-gitter
      if: ${{ steps.info.outputs.already-installed == 'false' }}
      env:
        BINDIR: "${{ steps.info.outputs.target-path }}"
        INPUT_VERSION: "${{ inputs.version}}"
      run: |
        if [ "${INPUT_VERSION}" = "latest" ]; then
          curl -s https://raw.githubusercontent.com/lindell/multi-gitter/master/install.sh | sh
        else
          curl -s https://raw.githubusercontent.com/lindell/multi-gitter/master/install.sh | sh -s -- -d "v${INPUT_VERSION}"
        fi
        echo "${BINDIR}" >> "$GITHUB_PATH"
      shell: sh
