---
name: 'Setup multi-gitter'
author: Yevhen Fabizhevskyi
description: 'This action installs multi-gitter CLI tool.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'multi-gitter version.'
    required: false
    default: '0.43.2'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        MULTI_GITTER_INSTALLED=$(if command -v multi-gitter >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "MULTI_GITTER_INSTALLED=$MULTI_GITTER_INSTALLED" >> $GITHUB_OUTPUT
        multi_gitter_path="$GITHUB_WORKSPACE/multi-gitter"
        mkdir -p $multi_gitter_path
        echo "MULTI_GITTER_PATH=$multi_gitter_path" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install multi-gitter
      if: ${{ steps.info.outputs.MULTI_GITTER_INSTALLED == 'false' }}
      run: curl -s https://raw.githubusercontent.com/lindell/multi-gitter/master/install.sh | sh -s -- v${{ inputs.version}}
      shell: sh
      working-directory: ${{ steps.info.outputs.MULTI_GITTER_PATH }}
