---
name: "Setup multi-gitter"
author: Yevhen Fabizhevskyi
description: "This action installs multi-gitter CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: multi-gitter version. Defaults to the latest version.
    required: false
    default: "latest"
  force:
    description: |
      If "false" skips installation if multi-gitter is already installed. If
      "true" installs multi-gitter in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether multi-gitter was installed or not.
    value: "${{ steps.install-multi-gitter.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      env:
        INPUT_VERSION: "${{ inputs.version }}"
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_VERSION}" "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Install multi-gitter
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-multi-gitter
      env:
        # Env var needed for the correct multi-gitter installation. Should not
        # be renamed.
        BINDIR: "${{ steps.info.outputs.bin-path }}"
        INPUT_VERSION: "${{ inputs.version}}"
      run: ./install-multi-gitter.sh "${INPUT_VERSION}" "${BINDIR}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Print version
      run: multi-gitter version
      shell: sh
