---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  setup-multi-gitter:
    name: Setup multi-gitter
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows", "macos"]
        version: ["0.47.3", "0.47.0", "0.46.0", "0.45.0", "0.44.2"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: multi-gitter version
