---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 1"

defaults:
  run:
    shell: sh

jobs:
  setup-multi-gitter:
    name: Setup multi-gitter
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows", "macos"]
        version: ["0.49.1", "latest"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup multi-gitter
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: multi-gitter version
