---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  setup-multi-gitter:
    name: Setup multi-gitter
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        version: ['0.43.2', '0.43.1', '0.43.0', '0.42.4', '0.42.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: multi-gitter version
        shell: sh
