---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - action.yml
  push:
    branches:
      - main
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch: {}

defaults:
  run:
    shell: sh

jobs:
  get-versions:
    name: Get 3 latest versions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      versions: ${{ steps.prepare-list.outputs.versions }}
    steps:
      - name: Prepare list
        id: prepare-list
        run: |
          url="https://api.github.com/repos/lindell/multi-gitter/releases"
          versions=$(curl -s "${url}" | jq -c '[.[0:3][].tag_name] | map(sub("^v"; "")) | . += ["latest"]')
          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
  setup-multi-gitter:
    name: Setup multi-gitter
    needs: [get-versions]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup multi-gitter
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Print version
        run: multi-gitter version
