---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - action.yml
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

defaults:
  run:
    shell: sh

jobs:
  setup-multi-gitter:
    name: Setup multi-gitter
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        # TODO: Add Windows once the following issue is resolved:
        # https://github.com/lindell/multi-gitter/issues/489
        os: ["ubuntu", "macos"]
        version: ["0.52.0", "latest"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup multi-gitter
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Print version
        run: multi-gitter version
